# Generated by Django 6.0.4 on 2026-04-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycsubmission",
            name="reviewer_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
